services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: richi
      POSTGRES_PASSWORD: richi
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Backend/initdb.sh:/docker-entrypoint-initdb.d/init-user-db.sh

  backend:  
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    env_file: ./Backend/.env          
    container_name: my_backend
    ports:
      - "3001:3001"
    volumes:
      - ./Backend/session.txt:/app_backend/session.txt
    depends_on:
      - postgres

  frontend:
    build: 
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: my_frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend   

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"   
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf 

volumes:
  postgres_data:
